print("########################### \n")
print("#                         # \n")
print("#     Nazla Salsabila     # \n")
print("#      2410817320001      # \n")
print("#                         # \n")
print("########################### \n")